- build:       gontinuum
  description: Build project gontinuum
  default:     run

- properties:
    name:       "gontinuum"
    version:    "0.1.0"
    bin_dir:    "bin"
    src_dir:    "src"
    main:       "#{src_dir}/#{name}.go"
    etc_dir:    "etc"
    etc_file:   "#{etc_dir}/#{name}.yml"
    args:       :etc_file

- target:      bin
  description: Make binary executable
  script:
  - rm: "#{bin_dir}/#{name}"
  - "go build -o #{bin_dir}/#{name} #{main}"

- target:      run
  depends:     bin
  description: Run gontinuum
  script:
  - "#{bin_dir}/#{name} #{args}"
