# NeON build file (http://github.com/c4s4/neon)

extends:
- c4s4/build/golang.yml
- c4s4/build/release.yml

properties:
  NAME: 'continuum'
  LIBRARIES:
  - 'github.com/mitchellh/gox'
  - 'gopkg.in/yaml.v1'

targets:

  run:
    doc: Run continuum
    depends: bin
    steps:
    - $: ['build/continuum', 'continuum.yml']
