- build:       gontinuum
  description: Build project gontinuum
  default:     run

- properties:
    name:        "gontinuum"
    package:     "github.com/c4s4/#{name}"
    version:     "0.1.0"
    build_dir:   "build"
    bin_dir:     "bin"
    src_dir:     "src"
    main:        "#{src_dir}/#{package}/#{name}.go"
    etc_dir:     "etc"
    etc_file:    "#{etc_dir}/#{name}.yml"
    args:        :etc_file
    clean_dirs:  :build_dir
    clean_files: ["#{bin_dir}/#{name}"]

- target:      bin
  description: Make binary executable
  script:
  - print: "Building project #{name}..."
  - rm: "#{bin_dir}/#{name}"
  - "go build -o #{bin_dir}/#{name} #{src_dir}/#{package}/*.go"

- target:      run
  depends:     bin
  description: Run gontinuum
  script:
  - "#{bin_dir}/#{name} #{args}"

- target:      test
  depends:     virtualenv
  description: Run unit tests
  script:
  - "go test #{package}"

- target:      doc
  description: Generate code documentation
  script:
  - "godoc #{package}"

- target:      virtualenv
  description: Check that we are running in virtualenv
  script:
  - if: "ENV['VIRTUAL_ENV'] != base"
    then:
    - raise: "You are not running in the project's Virtualenv, aborting"
    else:
    - print: "You are running in the project's Virtualenv, please proceed"

- target:      clean
  description: Clean generated files
  script:
  - rmdir: :clean_dirs
  - rm:    :clean_files
